---
- hosts: all
  tasks:
  #- name: sacar las credenciales del suscription ID de Azure
  - name: Montar la imagen appVM con Podman 
      collections:
        - containers.podman
      containers.podman.podman_image:
        name: "appVM"
        path: "/app-vm/Containerfile"
        build:
    